alt: Curved fabric swatches in neutral and warm tones
caption: Curved fabric swatches in neutral and warm tones.
attribution: |
  Photo by <a href="https://unsplash.com/@theshubhamdhage?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Shubham Dhage</a> on <a href="https://unsplash.com/photos/curved-fabric-swatches-in-various-neutral-and-warm-tones-AzKnjOs3xNk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
